version: '3.9'

services:
  db-service:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: offre_emploi
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  spring-server:
    image: spring-server
    container_name: spring-server
    environment:
      MYSQL_DATABASE: mysql
      SPRING_DATASOURCE_URL: "jdbc:mysql://db-service:3306/offre_emploi?createDatabaseIfNotExist=true"

    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db-service

  extractor-service:
    image: job-extractor
    ports:
      - 8000:8000
    networks:
      - app-network

  front-service:
    image: job-front
    ports:
      - "80:80"
    networks:
      app-network:
    depends_on:
      - spring-server
      - extractor-service
volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
