name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            # Update the system and install Docker if not installed
            sudo yum update -y
            if ! command -v docker &> /dev/null; then
              sudo amazon-linux-extras install docker
              sudo service docker start
              sudo usermod -a -G docker ec2-user
            fi

            # Create a custom Docker network
            docker network create my_network

            # Remove old MySQL container if exists
            docker rm -f mysql-container || true

            # Run the MySQL container with volume for persistent data
            docker run -d --name mysql-container \
              -e MYSQL_ROOT_PASSWORD=root \
              -e MYSQL_DATABASE=offre_emploi \
              -e MYSQL_USER=user \
              -e MYSQL_PASSWORD=password \
              -v mysql-data:/var/lib/mysql \
              --network my_network \
              -p 3306:3306 \
              mysql:latest

            # Remove old backend container if exists
            docker rm -f emploi-back || true

            # Pull the latest backend image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/emploi-back:latest

            # Run the backend container
            docker run -d --name emploi-back \
              -p 8080:8080 \
              --network my_network \
              --env SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/offre_emploi \
              --env SPRING_DATASOURCE_USERNAME=user \
              --env SPRING_DATASOURCE_PASSWORD=password \
              --env SPRING_MAIL_HOST=smtp.gmail.com \
              ${{ secrets.DOCKER_USERNAME }}/emploi-back:latest
          EOF
